<?php

namespace Database\Seeders\Definitions;

use App\Enum\MenuTypeEnum;
use App\Enum\PlanConditionTypeEnum;

final class PlanTemplate
{
    public static function getDefinitions(): array
    {
        return [
            'cut_color' => [
                'name'           => 'カット＋カラー',
                'description'    => 'カットとカラーがセットになったお得なプランです。',
                'total_duration' => 135,
                'regular_price'  => 12000,
                'selling_price'  => 10000,
                'condition_type' => PlanConditionTypeEnum::FIRST_VISIT->value,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::COLOR],
            ],
            'cut_color_treatment' => [
                'name'           => 'カット＋カラー＋トリートメント',
                'description'    => 'カット・カラー・トリートメントのフルセットプラン。',
                'total_duration' => 165,
                'regular_price'  => 16000,
                'selling_price'  => 13000,
                'condition_type' => PlanConditionTypeEnum::WEEKDAY->value,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::COLOR, MenuTypeEnum::TREATMENT],
            ],
            'cut_perm' => [
                'name'           => 'カット＋パーマ',
                'description'    => 'カットとパーマのセットプラン。',
                'total_duration' => 135,
                'regular_price'  => 13000,
                'selling_price'  => 11000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::PERM],
            ],
            'full_care' => [
                'name'           => 'フルケアプラン',
                'description'    => 'カット・カラー・トリートメント・ヘッドスパの総合プラン。',
                'total_duration' => 210,
                'regular_price'  => 22000,
                'selling_price'  => 18000,
                'condition_type' => PlanConditionTypeEnum::PERIOD->value,
                'valid_from'     => now()->copy()->startOfMonth()->format('Y-m-d'),
                'valid_to'       => now()->copy()->endOfMonth()->format('Y-m-d'),
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::COLOR, MenuTypeEnum::TREATMENT, MenuTypeEnum::HEAD_SPA],
            ],
            'cut_head_spa' => [
                'name'           => 'カット＋ヘッドスパ',
                'description'    => 'カットと頭皮ケアのヘッドスパがセットになったプラン。',
                'total_duration' => 105,
                'regular_price'  => 8000,
                'selling_price'  => 7000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::HEAD_SPA],
            ],
            'cut_straightening' => [
                'name'           => 'カット＋縮毛矯正',
                'description'    => 'カットと縮毛矯正のセット。くせ毛をストレートに。',
                'total_duration' => 165,
                'regular_price'  => 16000,
                'selling_price'  => 14000,
                'condition_type' => PlanConditionTypeEnum::WEEKEND->value,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::STRAIGHTENING],
            ],
            'cut_straightening_treatment' => [
                'name'           => 'カット＋縮毛矯正＋トリートメント',
                'description'    => '縮毛矯正と髪質ケアまで含んだフルプラン。',
                'total_duration' => 195,
                'regular_price'  => 20000,
                'selling_price'  => 17000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::STRAIGHTENING, MenuTypeEnum::TREATMENT],
            ],
            'color_treatment' => [
                'name'           => 'カラー＋トリートメント',
                'description'    => 'カラーと髪質ケアのトリートメントセット。',
                'total_duration' => 120,
                'regular_price'  => 12000,
                'selling_price'  => 10000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::COLOR, MenuTypeEnum::TREATMENT],
            ],
            'perm_treatment' => [
                'name'           => 'パーマ＋トリートメント',
                'description'    => 'パーマと髪質ケアのトリートメントセット。',
                'total_duration' => 120,
                'regular_price'  => 13000,
                'selling_price'  => 11000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::PERM, MenuTypeEnum::TREATMENT],
            ],
            'mens_cut_shaving' => [
                'name'           => 'メンズカット＋シェービング',
                'description'    => 'メンズカットと首周りシェービングのセット。',
                'total_duration' => 50,
                'regular_price'  => 5500,
                'selling_price'  => 4800,
                'condition_type' => PlanConditionTypeEnum::FIRST_VISIT->value,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::MENS_CUT, MenuTypeEnum::SHAVING],
            ],
            'cut_color_head_spa' => [
                'name'           => 'カット＋カラー＋ヘッドスパ',
                'description'    => 'カット・カラーにヘッドスパまで付いた贅沢プラン。',
                'total_duration' => 195,
                'regular_price'  => 19500,
                'selling_price'  => 16000,
                'condition_type' => PlanConditionTypeEnum::WEEKDAY->value,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::COLOR, MenuTypeEnum::HEAD_SPA],
            ],
            'cut_hair_set' => [
                'name'           => 'カット＋ヘアセット',
                'description'    => 'カットとヘアセットのセット。結婚式・パーティ向け。',
                'total_duration' => 120,
                'regular_price'  => 8500,
                'selling_price'  => 7500,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::HAIR_SET],
            ],
            'retouch_color_treatment' => [
                'name'           => 'リタッチカラー＋トリートメント',
                'description'    => '根元リタッチとトリートメントで色持ちと髪質をケア。',
                'total_duration' => 90,
                'regular_price'  => 9000,
                'selling_price'  => 7800,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::RETOUCH_COLOR, MenuTypeEnum::TREATMENT],
            ],
            'cut_eyebrow' => [
                'name'           => 'カット＋眉カット',
                'description'    => 'カットと眉の整えがセットになったプラン。',
                'total_duration' => 55,
                'regular_price'  => 4500,
                'selling_price'  => 4000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::EYEBROW_CUT],
            ],
            'straightening_treatment' => [
                'name'           => '縮毛矯正＋トリートメント',
                'description'    => '縮毛矯正と髪質ケアのトリートメントセット。',
                'total_duration' => 150,
                'regular_price'  => 16000,
                'selling_price'  => 14000,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::STRAIGHTENING, MenuTypeEnum::TREATMENT],
            ],
            'cut_bang' => [
                'name'           => 'カット＋前髪カット',
                'description'    => 'カットと前髪の整えがセット。',
                'total_duration' => 60,
                'regular_price'  => 5000,
                'selling_price'  => 4500,
                'condition_type' => null,
                'valid_from'     => null,
                'valid_to'       => null,
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::BANG_CUT],
            ],
            'cut_color_perm' => [
                'name'           => 'カット＋カラー＋パーマ',
                'description'    => 'カット・カラー・パーマのフルチェンジプラン。',
                'total_duration' => 210,
                'regular_price'  => 25000,
                'selling_price'  => 21000,
                'condition_type' => PlanConditionTypeEnum::PERIOD->value,
                'valid_from'     => now()->copy()->startOfMonth()->format('Y-m-d'),
                'valid_to'       => now()->copy()->endOfMonth()->format('Y-m-d'),
                'menu_types'     => [MenuTypeEnum::CUT, MenuTypeEnum::COLOR, MenuTypeEnum::PERM],
            ],
        ];
    }
}
